services:
  # Dienst 1: Der NonPlusUltra Bot (Hintergrund-Dienst)
  - type: worker
    name: nonplusultra-bot
    env: python
    buildCommand: "pip install -r requirements.txt && sudo apt-get update && sudo apt-get install -y redis-server"
    startCommand: "redis-server --daemonize yes && python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - fromGroup: nonplusultra-secrets

  # Dienst 2: Das Firefly Dashboard (Web-Dienst, vorerst deaktiviert)
  # Diesen Teil werden wir aktivieren, sobald das Dashboard gebaut ist.
  # - type: web
  #   name: firefly-dashboard
  #   env: python
  #   buildCommand: "pip install -r requirements.txt"
  #   startCommand: "gunicorn dashboard_app.main:server" # Beispielhafter Startbefehl
  #   envVars:
  #     - key: PYTHON_VERSION
  #       value: 3.12.1
  #     - fromGroup: nonplusultra-secrets

# Umgebungsvariablen-Gruppe für alle Dienste
envVarGroups:
  - name: nonplusultra-secrets
    envVars:
      - key: QUICKNODE_RPC_URL
        sync: false
      - key: QUICKNODE_WSS_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: GOOGLE_CLOUD_PROJECT
        sync: false
      - key: UPSTASH_REDIS_URL
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON # Für Firestore-Authentifizierung auf dem Server
        sync: false